<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PackageId>WireMock.Net.Google.Protobuf</PackageId>
        <Description>WireMock.Net extension for statically typed GRPC mocking with Google.Protobuf library</Description>
        <Authors>Stepami</Authors>
        <Company>N/A</Company>
        <Copyright>Copyright © Stepami 2026</Copyright>
        <RepositoryUrl>https://github.com/Stepami/wiremock-protobuf</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/Stepami/wiremock-protobuf</PackageProjectUrl>
        <Title>WireMock.Net.Google.Protobuf</Title>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageTags>tdd;mock;grpc;proto;protobuf;wiremock;test;server;unittest</PackageTags>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.35.1"/>
        <PackageReference Include="WireMock.Net" Version="2.13.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="../LICENSE" Pack="true" Visible="false" PackagePath=""/>
        <None Include="../readme.md" Pack="true" Visible="false" PackagePath=""/>
        <None Include="../icon.png" Pack="true" Visible="false" PackagePath=""/>
    </ItemGroup>

</Project>
